name 'Learn_Chef_Httpd'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures Learn_Chef_Httpd'
long_description 'Installs/Configures Learn_Chef_Httpd'
version '0.1.0'
depends 'Learn_Chef_Software'
